### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by bonelifer** [phpbb-de/phpbb-ext-movemessage#2]
There should be an optional comment field, so moderators can add a reason for moving the topic.

**Comment by nickvergessen** [comment]
That should be added to phpBB itself then?

**Comment by bonelifer** [comment]
Was thinking it should be here since it's a comment on why something was moved.

**Comment by Crizz0** [comment]
But if you move a topic, what other reason than "was in wrong forum" should it be?

**Comment by Leinad4Mind** [comment]
Sorry to use this issue, but I guess its better then create a new one.
Does this extension have on the message saying from where to where was move and by who. Have a link to move it back to the last place? That way I could click on "Move Topic Back" and it would move to the last forum.
Because sometimes I move a topic that has bad informations and need to be fixed, to a "Fixing" forum and then if I had that "Move Topic Back" it was just a matter of click on it and the topic would be automatically moved to the right section where it was created before.

Best Regards
